// Package export renders active memories into generated projections —
// AGENTS.md / CLAUDE.md / .cursor/rules instruction blocks, or JSON (prd.md
// §10.4). Projections are clearly marked generated artifacts, never the source
// of truth.
package export

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/AndreasSteinerPF/team-memory/internal/index"
)

const (
	beginMarker = "<!-- BEGIN TeamMemory (generated by `tm export`; do not edit) -->"
	endMarker   = "<!-- END TeamMemory -->"
)

// Markdown renders rows as a generated instruction block. title is the heading.
func Markdown(rows []index.IndexedMemory, title string) string {
	var b strings.Builder
	b.WriteString(beginMarker + "\n")
	fmt.Fprintf(&b, "## %s\n\n", title)
	if len(rows) == 0 {
		b.WriteString("_No active memories yet._\n")
	}
	for _, m := range rows {
		fmt.Fprintf(&b, "- **[%s] %s**", m.Enforcement, m.Title)
		if guidance := firstNonEmpty(m.Guidance, m.Summary); guidance != "" {
			fmt.Fprintf(&b, " — %s", guidance)
		}
		if len(m.EffectiveScope) > 0 {
			fmt.Fprintf(&b, " (scope: `%s`)", strings.Join(m.EffectiveScope, "`, `"))
		}
		b.WriteString("\n")
	}
	b.WriteString(endMarker + "\n")
	return b.String()
}

// JSON renders rows as indented JSON.
func JSON(rows []index.IndexedMemory) ([]byte, error) {
	return json.MarshalIndent(rows, "", "  ")
}

func firstNonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}
