// Package export renders active memories into generated projections —
// AGENTS.md / CLAUDE.md / .cursor/rules instruction blocks, or JSON (prd.md
// §10.4). Projections are clearly marked generated artifacts, never the source
// of truth.
package export

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/AndreasSteinerPF/team-memory/internal/index"
)

const (
	beginMarker = "<!-- BEGIN TeamMemory (generated by `tm export`; do not edit) -->"
	endMarker   = "<!-- END TeamMemory -->"
)

// Instructions returns the flavor-specific usage preamble (prd.md §10.4): when
// agents should call tm_check_action / tm_propose / tm_observe. The "claude"
// flavor notes that edit-time checks are automatic via the PreToolUse hook;
// other flavors instruct a voluntary check before edits.
func Instructions(flavor string) string {
	var b strings.Builder
	b.WriteString("These memories are validated project judgment from prior agent work in this repo. Treat `warning` and `requirement` entries as policy.\n\n")
	if flavor == "claude" {
		b.WriteString("- Edit-time checks run automatically via the TeamMemory PreToolUse hook. Before planning multi-file work, call the `tm_check_action` MCP tool with the target paths.\n")
	} else {
		b.WriteString("- Before editing files, call the `tm_check_action` MCP tool (or `tm check-action --path <file>`) with the paths you are about to change.\n")
	}
	b.WriteString("- When you discover durable project judgment — a non-obvious failure, a hidden constraint, a fragile area, a stale doc, or an undocumented decision — record it with `tm_propose`. Do not record session state, trivia, or facts derivable from the code.\n")
	b.WriteString("- When your work bears on a memory shown to you, react with `tm_observe`: `confirm` with evidence, `contradict` with evidence, `adjust_scope`, or `mark_stale`.\n")
	return b.String()
}

// Markdown renders rows as a generated instruction block. title is the heading;
// instructions is the usage preamble (may be empty).
func Markdown(rows []index.IndexedMemory, title, instructions string) string {
	var b strings.Builder
	b.WriteString(beginMarker + "\n")
	fmt.Fprintf(&b, "## %s\n\n", title)
	if instructions != "" {
		b.WriteString(instructions + "\n")
	}
	if len(rows) == 0 {
		b.WriteString("_No active memories yet._\n")
	}
	for _, m := range rows {
		fmt.Fprintf(&b, "- **[%s] %s**", m.Enforcement, m.Title)
		if guidance := firstNonEmpty(m.Guidance, m.Summary); guidance != "" {
			fmt.Fprintf(&b, " — %s", guidance)
		}
		if len(m.EffectiveScope) > 0 {
			fmt.Fprintf(&b, " (scope: `%s`)", strings.Join(m.EffectiveScope, "`, `"))
		}
		b.WriteString("\n")
	}
	b.WriteString(endMarker + "\n")
	return b.String()
}

// JSON renders rows as indented JSON.
func JSON(rows []index.IndexedMemory) ([]byte, error) {
	return json.MarshalIndent(rows, "", "  ")
}

func firstNonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}
